// Story data

// This is where you can write the story
export const story = [
  {
    id: 'scene-0',
    video: '/jadeStolen.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-1',
    video: '/jadeStolen2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-2',
    video: '/mayaChat.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-3',
    video: '/phoeAnw.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-4',
    video: '/mayaChat2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-5',
    video: '/phoeAnw2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-6',
    video: '/doorKnock.mp4',
    speaker: '',
    text: '',
    choices: ['open', 'leave it'],
    responses: ['', ''],
    nextEvents: ['scene-8', 'scene-7'],
  },
  {
    id: 'scene-7',
    video: '/lazyEnd.mp4',
    speaker: '',
    text: '',
    choices: ['restart', 'choose again'],
    responses: ['', ''],
    nextEvents: ['scene-0', 'scene-6'],
  },
  {
    id: 'scene-8',
    video: '/mission.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-9',
    video: '/mission2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-10',
    video: '/mission3.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-11',
    video: '/mission4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-12',
    video: '/mission5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-13',
    video: '/mission6.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-14',
    video: '/mission7.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-15',
    video: '/mission8.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-16',
    video: '/mission9.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-17',
    video: '/day0.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-18',
    video: '/rply.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-19',
    video: '/day1.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-20',
    video: '/day2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-21',
    video: '/day3.mp4',
    speaker: '',
    text: '',
    choices: ['Ask about the jade', 'Ask why pushed'],
    responses: ['', ''],
    nextEvents: ['scene-22', 'scene-28'],
  },
  {
    id: 'scene-22',
    video: '/day4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-23',
    video: '/day5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-24',
    video: '/day6.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-25',
    video: '/push0.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-26',
    video: '/push1.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-27',
    video: '/push2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-28',
    video: '/push0.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-29',
    video: '/push1.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-30',
    video: '/push2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-31',
    video: '/day4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-32',
    video: '/day5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-33',
    video: '/day6.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-34',
    video: '/evidence.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-35',
    video: '/new.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-36',
    video: '/hall1.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-37',
    video: '/hall2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-38',
    video: '/hall3.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-39',
    video: '/hall4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-40',
    video: '/hall5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
]
