export const story = [
  {
    id: 'scene-0',
    video: '/jadeStolen.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-1'],
  },
  {
    id: 'scene-1',
    video: '/jadeStolen2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-2'],
  },
  {
    id: 'scene-2',
    video: '/mayaChat.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-3'],
  },
  {
    id: 'scene-3',
    video: '/phoeAnw.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-4'],
  },
  {
    id: 'scene-4',
    video: '/mayaChat2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-5'],
  },
  {
    id: 'scene-5',
    video: '/phoeAnw2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-6'],
  },
  {
    id: 'scene-6',
    video: '/doorKnock.mp4',
    speaker: '',
    text: '',
    choices: ['open', 'leave it'],
    responses: ['', ''],
    nextEvents: ['scene-8', 'scene-7'],
  },
  {
    id: 'scene-7',
    video: '/lazyEnd.mp4',
    speaker: '',
    text: '',
    choices: ['restart', 'choose again'],
    responses: ['', ''],
    nextEvents: ['scene-0', 'scene-6'],
  },
  {
    id: 'scene-8',
    video: '/mission.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-9'],
  },
  {
    id: 'scene-9',
    video: '/mission2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-10'],
  },
  {
    id: 'scene-10',
    video: '/mission3.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-11'],
  },
  {
    id: 'scene-11',
    video: '/mission4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-12'],
  },
  {
    id: 'scene-12',
    video: '/mission5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-13'],
  },
  {
    id: 'scene-13',
    video: '/mission6.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-14'],
  },
  {
    id: 'scene-14',
    video: '/mission7.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-15'],
  },
  {
    id: 'scene-15',
    video: '/mission8.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-16'],
  },
  {
    id: 'scene-16',
    video: '/mission9.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-17'],
  },
  {
    id: 'scene-17',
    video: '/day0.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-18'],
  },
  {
    id: 'scene-18',
    video: '/rply.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-19'],
  },
  {
    id: 'scene-19',
    video: '/day1.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-20'],
  },
  {
    id: 'scene-20',
    video: '/day2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-21'],
  },
  {
    id: 'scene-21',
    video: '/day3.mp4',
    speaker: '',
    text: '',
    choices: ['Ask about the jade', 'Ask why pushed'],
    responses: ['', ''],
    nextEvents: ['scene-22', 'scene-28'],
  },
  {
    id: 'scene-22',
    video: '/day4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-23'],
  },
  {
    id: 'scene-23',
    video: '/day5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-24'],
  },
  {
    id: 'scene-24',
    video: '/day6.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-25'],
  },
  {
    id: 'scene-25',
    video: '/push0.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-26'],
  },
  {
    id: 'scene-26',
    video: '/push1.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-27'],
  },
  {
    id: 'scene-27',
    video: '/push2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-34'],
  },
  {
    id: 'scene-28',
    video: '/push0.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-29'],
  },
  {
    id: 'scene-29',
    video: '/push1.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-30'],
  },
  {
    id: 'scene-30',
    video: '/push2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-31'],
  },
  {
    id: 'scene-31',
    video: '/day4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-32'],
  },
  {
    id: 'scene-32',
    video: '/day5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-33'],
  },
  {
    id: 'scene-33',
    video: '/day6.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-34'],
  },
  {
    id: 'scene-34',
    video: '/evidence.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-35'],
  },
  {
    id: 'scene-35',
    video: '/new.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-36',
    video: '/hall1.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-37'],
  },
  {
    id: 'scene-37',
    video: '/hall2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-38'],
  },
  {
    id: 'scene-38',
    video: '/hall3.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-39'],
  },
  {
    id: 'scene-39',
    video: '/hall4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-40'],
  },
  {
    id: 'scene-40',
    video: '/hall5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: [],
  },
  {
    id: 'scene-41',
    video: '/begin.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-42'],
  },
  {
    id: 'scene-42',
    video: '/begin2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-43'],
  },
  {
    id: 'scene-43',
    video: '/begin3.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-44'],
  },
  {
    id: 'scene-44',
    video: '/begin4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-45'],
  },
  {
    id: 'scene-45',
    video: '/begin5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-46'],
  },
  {
    id: 'scene-46',
    video: '/begin6.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-47'],
  },
  {
    id: 'scene-47',
    video: '/begin7.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-48'],
  },
  {
    id: 'scene-48',
    video: '/begin8.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-49'],
  },
  {
    id: 'scene-49',
    video: '/begin9.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-50'],
  },
  {
    id: 'scene-50',
    video: '/begin10.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-51'],
  },
  {
    id: 'scene-51',
    video: '/begin11.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-52'],
  },
  {
    id: 'scene-52',
    video: '/begin12.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-53'],
  },
  {
    id: 'scene-53',
    video: '/begin13.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-54'],
  },
  {
    id: 'scene-54',
    video: '/begin14.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-55'],
  },
  {
    id: 'scene-55',
    video: '/begin15.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-56'],
  },
  {
    id: 'scene-56',
    video: '/begin16.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-57'],
  },
  {
    id: 'scene-57',
    video: '/begin17.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-58'],
  },
  {
    id: 'scene-58',
    video: '/begin18.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-59'],
  },
  {
    id: 'scene-59',
    video: '/begin19.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-60'],
  },
  {
    id: 'scene-60',
    video: '/begin20.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-61'],
  },
  {
    id: 'scene-61',
    video: '/firstRound.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-62'],
  },
  {
    id: 'scene-62',
    video: '/firstRound2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-63'],
  },
  {
    id: 'scene-63',
    video: '/firstRound3.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-64'],
  },
  {
    id: 'scene-64',
    video: '/firstRound4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-65'],
  },
  {
    id: 'scene-65',
    video: '/firstRound5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-66'],
  },
  {
    id: 'scene-66',
    video: '/firstRound6.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-67'],
  },
  {
    id: 'scene-67',
    video: '/firstRound7.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-68'],
  },
  {
    id: 'scene-68',
    video: '/firstRound8.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-69'],
  },
  {
    id: 'scene-69',
    video: '/firstRound9.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-70'],
  },
  {
    id: 'scene-70',
    video: '/firstRound10.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-71'],
  },
  {
    id: 'scene-71',
    video: '/firstRound11.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-72'],
  },
  {
    id: 'scene-72',
    video: '/firstRound12.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-73'],
  },
  {
    id: 'scene-73',
    video: '/firstRound13.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-74'],
  },
  {
    id: 'scene-74',
    video: '/firstRound14.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-75'],
  },
  {
    id: 'scene-75',
    video: '/firstRound15.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-76'],
  },
  {
    id: 'scene-76',
    video: '/firstRound16.mp4',
    speaker: '',
    text: '',
    choices: ['Key record', 'Jade with blood'],
    responses: [],
    nextEvents: ['scene-77', 'scene-88'],
  },
  {
    id: 'scene-77',
    video: '/firstRound17.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-78'],
  },
  {
    id: 'scene-78',
    video: '/firstRound18.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-79'],
  },
  {
    id: 'scene-79',
    video: '/firstRound19.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-80'],
  },
  {
    id: 'scene-80',
    video: '/firstRound20.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-81'],
  },
  {
    id: 'scene-81',
    video: '/firstRound21.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-82'],
  },
  {
    id: 'scene-82',
    video: '/firstRound22.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-83'],
  },
  {
    id: 'scene-83',
    video: '/firstRound23.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-84'],
  },
  {
    id: 'scene-84',
    video: '/firstRound24.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-85'],
  },
  {
    id: 'scene-85',
    video: '/firstRound25.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-86'],
  },
  {
    id: 'scene-86',
    video: '/objection.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-87'],
  },
  {
    id: 'scene-87',
    video: '/objection2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-103'],
  },
  {
    id: 'scene-88',
    video: '/firstRound25.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-89'],
  },
  {
    id: 'scene-89',
    video: '/objection.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-90'],
  },
  {
    id: 'scene-90',
    video: '/objection2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-91'],
  },
  {
    id: 'scene-91',
    video: '/firstRound24.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-92'],
  },
  {
    id: 'scene-92',
    video: '/firstRound17.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-93'],
  },
  {
    id: 'scene-93',
    video: '/firstRound18.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-94'],
  },
  {
    id: 'scene-94',
    video: '/firstRound19.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-95'],
  },
  {
    id: 'scene-96',
    video: '/firstRound20.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-97'],
  },
  {
    id: 'scene-97',
    video: '/firstRound21.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-98'],
  },
  {
    id: 'scene-99',
    video: '/firstRound22.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-100'],
  },
  {
    id: 'scene-101',
    video: '/firstRound23.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-102'],
  },
  {
    id: 'scene-103',
    video: '/objection3.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-104'],
  },
  {
    id: 'scene-104',
    video: '/juezhan1.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-105'],
  },
  {
    id: 'scene-105',
    video: '/juezhan2.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-106'],
  },
  {
    id: 'scene-106',
    video: '/juezhan3.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-107'],
  },
  {
    id: 'scene-107',
    video: '/juezhan4.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-108'],
  },
  {
    id: 'scene-108',
    video: '/juezhan5.mp4',
    speaker: '',
    text: '',
    choices: [],
    responses: [],
    nextEvents: ['scene-109'],
  },
  {
    id: 'scene-109',
    video: '/juezhan6.mp4',
    speaker: '',
    text: '',
    choices: ['restart'],
    responses: [],
    nextEvents: ['scene-1'],
  },
]
